// Standard Starlight docs collection. Generated markdown is written into
// src/content/docs/ (by `sddc repo wiki build`), the native Starlight location.
// We do NOT load from an out-of-tree docs/wiki via a glob base: a base outside
// the Astro root makes Starlight's autogenerated sidebar build phantom groups
// from the path traversal (.. > docs > wiki > ...). The content still lives in
// the repo, committed and reviewable, just under wiki-site/.
import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
